name: Build CV

on:
  # schedule:
  #   - cron: '0 6 1 1,7 *'  # every Monday at 6 AM UTC
  workflow_dispatch:       # allow manual trigger
  push:
    paths:
      - cv.tex

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v4
      with:
        root_file: cv.tex
        latexmk_use_xelatex: true

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: CV
        path: cv.pdf
