name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv.tex
          extra_system_packages: "texlive-bibtex-extra biber"
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cv.pdf
